<a href="https://colab.research.google.com/github/dpratap17/DeepLearningLab/blob/main/DL_Lab_Exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THEORETICAL BACKGROUND:
Tensors are multi-dimensional arrays that generalize vectors and matrices to
higher dimensions. They are the fundamental data structure in deep learning:
- 0D tensor (scalar): A single number
- 1D tensor (vector): An array of numbers
- 2D tensor (matrix): A table of numbers
- 3D+ tensors: Higher-dimensional arrays

PyTorch tensors support GPU acceleration and automatic differentiation,
making them ideal for deep learning.
NumPy arrays are CPU-based and widely
used for scientific computing.

In [1]:
#Importing necessary modules
import numpy as np
import torch

CONCEPT:

Tensors can be created in multiple dimensions to represent different types of data:
- 1D: Time series, audio signals, feature vectors
- 2D: Images (grayscale), tabular data, weight matrices
- 3D: RGB images, video frames, text embeddings (batch, sequence, features)

In [7]:
print("1. CREATING 1D, 2D, AND 3D TENSORS")
print("\n--- PyTorch ---")
pt_1d = torch.tensor([1, 2, 3, 4, 5])
pt_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
pt_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D Tensor: {pt_1d}, Shape: {pt_1d.shape}")
print(f"2D Tensor:\n{pt_2d}\nShape: {pt_2d.shape}")
print(f"3D Tensor:\n{pt_3d}\nShape: {pt_3d.shape}")

1. CREATING 1D, 2D, AND 3D TENSORS

--- PyTorch ---
1D Tensor: tensor([1, 2, 3, 4, 5]), Shape: torch.Size([5])
2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [4]:
print("\n--- NumPy ---")
np_1d = np.array([1, 2, 3, 4, 5])
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D Array: {np_1d}, Shape: {np_1d.shape}")
print(f"2D Array:\n{np_2d}\nShape: {np_2d.shape}")
print(f"3D Array:\n{np_3d}\nShape: {np_3d.shape}")


--- NumPy ---
1D Array: [1 2 3 4 5], Shape: (5,)
2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


CONCEPT:

Tensor operations form the building blocks of neural network computations:
- Element-wise operations: Applied independently to each element
- Dot product: Scalar result from two vectors
- Matrix multiplication: Core operation in neural network layers

MATHEMATICAL FORMULAS:

Element-wise addition: C[i] = A[i] + B[i]

Dot product: result = Σ(A[i] * B[i])

Matrix multiplication: C[i,j] = Σ(A[i,k] * B[k,j]

In [6]:
print("2. BASIC OPERATIONS")

# Create sample tensors
a_pt = torch.tensor([10, 20, 30])
b_pt = torch.tensor([1, 2, 3])
a_np = np.array([10, 20, 30])
b_np = np.array([1, 2, 3])

print("\n--- Element-wise Operations (PyTorch) ---")
print(f"a = {a_pt}, b = {b_pt}")
print(f"Addition: {a_pt + b_pt}")
print(f"Subtraction: {a_pt - b_pt}")
print(f"Multiplication: {a_pt * b_pt}")
print(f"Division: {a_pt / b_pt}")

print("\n--- Element-wise Operations (NumPy) ---")
print(f"a = {a_np}, b = {b_np}")
print(f"Addition: {a_np + b_np}")
print(f"Subtraction: {a_np - b_np}")
print(f"Multiplication: {a_np * b_np}")
print(f"Division: {a_np / b_np}")

print("\n--- Dot Product ---")
print(f"PyTorch dot product: {torch.dot(a_pt, b_pt)}")
print(f"NumPy dot product: {np.dot(a_np, b_np)}")

print("\n--- Matrix Multiplication ---")
mat1_pt = torch.tensor([[1, 2], [3, 4]])
mat2_pt = torch.tensor([[5, 6], [7, 8]])
mat1_np = np.array([[1, 2], [3, 4]])
mat2_np = np.array([[5, 6], [7, 8]])

print(f"PyTorch matmul:\n{torch.matmul(mat1_pt, mat2_pt)}")
print(f"PyTorch @ operator:\n{mat1_pt @ mat2_pt}")
print(f"NumPy matmul:\n{np.matmul(mat1_np, mat2_np)}")
print(f"NumPy @ operator:\n{mat1_np @ mat2_np}")

2. BASIC OPERATIONS

--- Element-wise Operations (PyTorch) ---
a = tensor([10, 20, 30]), b = tensor([1, 2, 3])
Addition: tensor([11, 22, 33])
Subtraction: tensor([ 9, 18, 27])
Multiplication: tensor([10, 40, 90])
Division: tensor([10., 10., 10.])

--- Element-wise Operations (NumPy) ---
a = [10 20 30], b = [1 2 3]
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]

--- Dot Product ---
PyTorch dot product: 140
NumPy dot product: 140

--- Matrix Multiplication ---
PyTorch matmul:
tensor([[19, 22],
        [43, 50]])
PyTorch @ operator:
tensor([[19, 22],
        [43, 50]])
NumPy matmul:
[[19 22]
 [43 50]]
NumPy @ operator:
[[19 22]
 [43 50]]


CONCEPT:

Indexing and slicing allow efficient access to tensor subsets without copying data:
- Basic indexing: Access specific elements or rows/columns
- Slicing: Extract contiguous regions using start:stop:step syntax
- Boolean masking: Filter elements based on conditions
- Advanced indexing: Use lists/tensors to select specific indices

SYNTAX:
-------
tensor[row, col]        # Single element

tensor[start:end]       # Slice from start to end-1

tensor[::step]          # Every step-th element

tensor[condition]       # Boolean mask

In [8]:
print("3. INDEXING AND SLICING")

tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(f"\nOriginal:\n{tensor}")
print(f"\n--- Basic Indexing ---")
print(f"Element at [1, 2]: {tensor[1, 2]}")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")

print(f"\n--- Slicing ---")
print(f"First 2 rows, first 3 cols:\n{tensor[:2, :3]}")
print(f"Every other element in row 1: {tensor[1, ::2]}")

print(f"\n--- Boolean Masking (PyTorch) ---")
mask = tensor > 6
print(f"Mask (elements > 6):\n{mask}")
print(f"Elements > 6: {tensor[mask]}")

print(f"\n--- Boolean Masking (NumPy) ---")
mask_np = array > 6
print(f"Elements > 6: {array[mask_np]}")

print(f"\n--- Advanced Indexing ---")
indices = torch.tensor([0, 2])
print(f"Rows 0 and 2:\n{tensor[indices]}")

3. INDEXING AND SLICING

Original:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

--- Basic Indexing ---
Element at [1, 2]: 7
First row: tensor([1, 2, 3, 4])
First column: tensor([1, 5, 9])

--- Slicing ---
First 2 rows, first 3 cols:
tensor([[1, 2, 3],
        [5, 6, 7]])
Every other element in row 1: tensor([5, 7])

--- Boolean Masking (PyTorch) ---
Mask (elements > 6):
tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
Elements > 6: tensor([ 7,  8,  9, 10, 11, 12])

--- Boolean Masking (NumPy) ---
Elements > 6: [ 7  8  9 10 11 12]

--- Advanced Indexing ---
Rows 0 and 2:
tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])


CONCEPT:

Shape manipulation is crucial for preparing data for neural networks:
- reshape(): Changes tensor shape, may copy data
- view(): Changes shape, shares memory (requires contiguous data)
- squeeze(): Removes dimensions of size 1
- unsqueeze(): Adds dimensions of size 1

KEY DIFFERENCES:

- view() is faster but requires contiguous memory
- reshape() always works but may copy data
- Use -1 in reshape/view to infer dimension automatically

In [10]:
print("4. RESHAPE, VIEW, SQUEEZE, UNSQUEEZE")

x = torch.arange(12)
print(f"\nOriginal tensor: {x}, Shape: {x.shape}")

print("\n--- .view() in PyTorch ---")
x_view = x.view(3, 4)
print(f"view(3, 4):\n{x_view}")
print(f"view(-1, 2) (infer dimension):\n{x.view(-1, 2)}")

print("\n--- .reshape() in PyTorch ---")
x_reshape = x.reshape(4, 3)
print(f"reshape(4, 3):\n{x_reshape}")

print("\n--- .reshape() in NumPy ---")
x_np = np.arange(12)
print(f"reshape(3, 4):\n{x_np.reshape(3, 4)}")

print("\n--- .unsqueeze() - Add dimension ---")
y = torch.tensor([1, 2, 3])
print(f"Original: {y}, Shape: {y.shape}")
print(f"unsqueeze(0): {y.unsqueeze(0)}, Shape: {y.unsqueeze(0).shape}")
print(f"unsqueeze(1): {y.unsqueeze(1)}, Shape: {y.unsqueeze(1).shape}")

print("\n--- .squeeze() - Remove dimension ---")
z = torch.tensor([[[1, 2, 3]]])
print(f"Original shape: {z.shape}")
print(f"After squeeze(): {z.squeeze()}, Shape: {z.squeeze().shape}")

print("\n--- NumPy expand_dims and squeeze ---")
y_np = np.array([1, 2, 3])
print(f"expand_dims(axis=0): {np.expand_dims(y_np, axis=0)}, Shape: {np.expand_dims(y_np, axis=0).shape}")
z_np = np.array([[[1, 2, 3]]])
print(f"squeeze(): {np.squeeze(z_np)}, Shape: {np.squeeze(z_np).shape}")


4. RESHAPE, VIEW, SQUEEZE, UNSQUEEZE

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), Shape: torch.Size([12])

--- .view() in PyTorch ---
view(3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
view(-1, 2) (infer dimension):
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

--- .reshape() in PyTorch ---
reshape(4, 3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

--- .reshape() in NumPy ---
reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

--- .unsqueeze() - Add dimension ---
Original: tensor([1, 2, 3]), Shape: torch.Size([3])
unsqueeze(0): tensor([[1, 2, 3]]), Shape: torch.Size([1, 3])
unsqueeze(1): tensor([[1],
        [2],
        [3]]), Shape: torch.Size([3, 1])

--- .squeeze() - Remove dimension ---
Original shape: torch.Size([1, 1, 3])
After squeeze(): tensor([1, 2, 3]), Shape: torch.Size([3])

--- NumPy 

CONCEPT:

Broadcasting allows operations between tensors of different shapes without
explicit replication. The smaller tensor is virtually "stretched" to match
the larger tensor's shape.

BROADCASTING RULES:

1. Compare dimensions from right to left
2. Dimensions are compatible if:
   - They are equal, OR
   - One of them is 1
3. Missing dimensions are treated as 1

In [11]:
print("5. BROADCASTING")

print("\n--- Example 1: Scalar with Vector ---")
a = torch.tensor([1, 2, 3])
b = 10
print(f"{a} + {b} = {a + b}")

print("\n--- Example 2: Vector with Matrix ---")
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
vector = torch.tensor([10, 20, 30])
print(f"Matrix:\n{matrix}")
print(f"Vector: {vector}")
print(f"Result:\n{matrix + vector}")

print("\n--- Example 3: Different Dimensions ---")
x = torch.ones(3, 1)
y = torch.ones(1, 4)
print(f"x shape: {x.shape}, y shape: {y.shape}")
print(f"Result shape: {(x + y).shape}")
print(f"Result:\n{x + y}")

print("\n--- NumPy Broadcasting ---")
a_np = np.array([[1, 2, 3], [4, 5, 6]])
b_np = np.array([10, 20, 30])
print(f"Result:\n{a_np + b_np}")

5. BROADCASTING

--- Example 1: Scalar with Vector ---
tensor([1, 2, 3]) + 10 = tensor([11, 12, 13])

--- Example 2: Vector with Matrix ---
Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Vector: tensor([10, 20, 30])
Result:
tensor([[11, 22, 33],
        [14, 25, 36]])

--- Example 3: Different Dimensions ---
x shape: torch.Size([3, 1]), y shape: torch.Size([1, 4])
Result shape: torch.Size([3, 4])
Result:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

--- NumPy Broadcasting ---
Result:
[[11 22 33]
 [14 25 36]]


CONCEPT:

Operations can either create new tensors or modify existing ones:
- Out-of-place: Creates new tensor, original unchanged (safer)
- In-place: Modifies original tensor directly (memory efficient)

PYTORCH CONVENTION:

Operations ending with underscore (_) are in-place: add_, mul_, etc.
Operations without underscore create new tensors: add, mul, etc.


Out-of-place: Uses more memory but safer for gradients
In-place: Saves memory but can break gradient computation

In [13]:
print("6. IN-PLACE vs OUT-OF-PLACE OPERATIONS")

print("\n--- Out-of-place (creates new tensor) ---")
x = torch.tensor([1, 2, 3])
print(f"Original: {x}")
y = x + 10
print(f"After y = x + 10:")
print(f"  x = {x} (unchanged)")
print(f"  y = {y} (new tensor)")

print("\n--- In-place (modifies original) ---")
x = torch.tensor([1, 2, 3])
print(f"Original: {x}")
x.add_(10)  # Note the underscore
print(f"After x.add_(10): {x} (modified)")

print("\n--- Common In-place Operations in PyTorch ---")
x = torch.tensor([1.0, 2.0, 3.0])
print(f"Original: {x}")
x.mul_(2)  # x *= 2
print(f"After mul_(2): {x}")
x.sub_(1)  # x -= 1
print(f"After sub_(1): {x}")
x.div_(2)  # x /= 2
print(f"After div_(2): {x}")

print("\n--- NumPy In-place Operations ---")
x_np = np.array([1, 2, 3])
print(f"Original: {x_np}")
x_np += 10
print(f"After += 10: {x_np}")

print("\n--- Warning: view() and in-place operations ---")
x = torch.tensor([[1, 2], [3, 4]])
y = x.view(4)
print(f"x:\n{x}")
print(f"y (view): {y}")
y[0] = 99
print(f"After y[0] = 99:")
print(f"  x:\n{x} (also changed! view shares memory)")
print(f"  y: {y}")

6. IN-PLACE vs OUT-OF-PLACE OPERATIONS

--- Out-of-place (creates new tensor) ---
Original: tensor([1, 2, 3])
After y = x + 10:
  x = tensor([1, 2, 3]) (unchanged)
  y = tensor([11, 12, 13]) (new tensor)

--- In-place (modifies original) ---
Original: tensor([1, 2, 3])
After x.add_(10): tensor([11, 12, 13]) (modified)

--- Common In-place Operations in PyTorch ---
Original: tensor([1., 2., 3.])
After mul_(2): tensor([2., 4., 6.])
After sub_(1): tensor([1., 3., 5.])
After div_(2): tensor([0.5000, 1.5000, 2.5000])

--- NumPy In-place Operations ---
Original: [1 2 3]
After += 10: [11 12 13]

--- Warning: view() and in-place operations ---
x:
tensor([[1, 2],
        [3, 4]])
y (view): tensor([1, 2, 3, 4])
After y[0] = 99:
  x:
tensor([[99,  2],
        [ 3,  4]]) (also changed! view shares memory)
  y: tensor([99,  2,  3,  4])
