<a href="https://colab.research.google.com/github/dpratap17/DeepLearningLab/blob/main/DL_Lab_Exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [7]:
print("1. CREATING 1D, 2D, AND 3D TENSORS")
print("\n--- PyTorch ---")
pt_1d = torch.tensor([1, 2, 3, 4, 5])
pt_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
pt_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D Tensor: {pt_1d}, Shape: {pt_1d.shape}")
print(f"2D Tensor:\n{pt_2d}\nShape: {pt_2d.shape}")
print(f"3D Tensor:\n{pt_3d}\nShape: {pt_3d.shape}")

1. CREATING 1D, 2D, AND 3D TENSORS

--- PyTorch ---
1D Tensor: tensor([1, 2, 3, 4, 5]), Shape: torch.Size([5])
2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [4]:
print("\n--- NumPy ---")
np_1d = np.array([1, 2, 3, 4, 5])
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"1D Array: {np_1d}, Shape: {np_1d.shape}")
print(f"2D Array:\n{np_2d}\nShape: {np_2d.shape}")
print(f"3D Array:\n{np_3d}\nShape: {np_3d.shape}")


--- NumPy ---
1D Array: [1 2 3 4 5], Shape: (5,)
2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [6]:
print("2. BASIC OPERATIONS")

# Create sample tensors
a_pt = torch.tensor([10, 20, 30])
b_pt = torch.tensor([1, 2, 3])
a_np = np.array([10, 20, 30])
b_np = np.array([1, 2, 3])

print("\n--- Element-wise Operations (PyTorch) ---")
print(f"a = {a_pt}, b = {b_pt}")
print(f"Addition: {a_pt + b_pt}")
print(f"Subtraction: {a_pt - b_pt}")
print(f"Multiplication: {a_pt * b_pt}")
print(f"Division: {a_pt / b_pt}")

print("\n--- Element-wise Operations (NumPy) ---")
print(f"a = {a_np}, b = {b_np}")
print(f"Addition: {a_np + b_np}")
print(f"Subtraction: {a_np - b_np}")
print(f"Multiplication: {a_np * b_np}")
print(f"Division: {a_np / b_np}")

print("\n--- Dot Product ---")
print(f"PyTorch dot product: {torch.dot(a_pt, b_pt)}")
print(f"NumPy dot product: {np.dot(a_np, b_np)}")

print("\n--- Matrix Multiplication ---")
mat1_pt = torch.tensor([[1, 2], [3, 4]])
mat2_pt = torch.tensor([[5, 6], [7, 8]])
mat1_np = np.array([[1, 2], [3, 4]])
mat2_np = np.array([[5, 6], [7, 8]])

print(f"PyTorch matmul:\n{torch.matmul(mat1_pt, mat2_pt)}")
print(f"PyTorch @ operator:\n{mat1_pt @ mat2_pt}")
print(f"NumPy matmul:\n{np.matmul(mat1_np, mat2_np)}")
print(f"NumPy @ operator:\n{mat1_np @ mat2_np}")

2. BASIC OPERATIONS

--- Element-wise Operations (PyTorch) ---
a = tensor([10, 20, 30]), b = tensor([1, 2, 3])
Addition: tensor([11, 22, 33])
Subtraction: tensor([ 9, 18, 27])
Multiplication: tensor([10, 40, 90])
Division: tensor([10., 10., 10.])

--- Element-wise Operations (NumPy) ---
a = [10 20 30], b = [1 2 3]
Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]

--- Dot Product ---
PyTorch dot product: 140
NumPy dot product: 140

--- Matrix Multiplication ---
PyTorch matmul:
tensor([[19, 22],
        [43, 50]])
PyTorch @ operator:
tensor([[19, 22],
        [43, 50]])
NumPy matmul:
[[19 22]
 [43 50]]
NumPy @ operator:
[[19 22]
 [43 50]]
